- name: Elastic search install && config
  hosts: elksrv
  vars:
    - kibana_conf: /etc/kibana/kibana.yml
    - filebeat_conf: /etc/filebeat/filebeat.yml
    - elastic_conf: /etc/elasticsearch/elasticsearch.yml
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: install nedeed pachage
      package:
        name:
          - curl
          - wget
          - openssl
          - xz-utils
          - ca-certificates
          - apt-transport-https
          - auditd
        state: present
        update_cache: true

    - name: prepare distrib directory
      file:
        path: /usr/share/distrib
        state: directory
        mode: "0754"

    - name: copy deb packages from local to remote
      copy:
        src: "./distrib/{{ item }}"
        dest: "/usr/share/distrib/"
      loop:
       - "elasticsearch-8.6.1-amd64.deb"
       - "kibana-8.6.1-amd64.deb"
       - "filebeat-8.6.1-amd64.deb"
       - "logstash-8.6.1-amd64.deb"

    - name: install elasticsearch
      apt:
        deb: "/usr/share/distrib/elasticsearch-8.6.1-amd64.deb"
        state: present
        update_cache: true

    - name: copy elasticsearch new conf
      copy:
        src: "./config/elasticsearch.yml"
        dest: "/etc/elasticsearch/elasticsearch.yml"
        owner: root
        group: elasticsearch
        mode: "0660"

    - name: restart elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
        enabled: true

    - name: install kibana
      apt:
        deb: "/usr/share/distrib/kibana-8.6.1-amd64.deb"
        state: present
        update_cache: true

    - name: kibana configuring
      lineinfile:
        path: "{{ kibana_conf }}"
        search_string: "{{ item.str }}"
        line: "{{ item.line }}"
      loop:
        - {str: 'server.host: "localhost"', line: 'server.host: "0.0.0.0"'}
        - {str: '#elasticsearch.hosts: ["http://localhost:9200"]', line: 'elasticsearch.hosts: ["http://localhost:9200"]'}

    - name: restart kibana
      systemd:
        name: kibana
        state: restarted
        enabled: true

    - name: start auditd
      systemd:
        name: auditd
        state: started
        enabled: true

    - name: install filebeat
      apt:
        deb: "/usr/share/distrib/filebeat-8.6.1-amd64.deb"
        state: present
        update_cache: true

    - name: filebeat configuring
      lineinfile:
        path: "{{ filebeat_conf }}"
        search_string: '  #host: "localhost:5601"'
        line: '  host: "localhost:5601"'

    - name: enable auditd filebeat module
      shell:
        cmd: "filebeat modules enable auditd && filebeat modules enable system"

    - name: config auditd filebeat module
      lineinfile:
        path: "/etc/filebeat/modules.d/auditd.yml"
        search_string: '    enabled: false'
        line: '    enabled: true'

    - name: copy system.yml to /etc/filebeat/modules.d (disabled by default, filebeat don't start with auditd)
      copy:
        src: "./config/system.yml"
        dest: "/etc/filebeat/modules.d/system.yml"
        owner: root
        group: root
        mode: "0644"
        backup: true

    - name: admin must check for kibana status
      pause:
        prompt: "ensure that kibana is running than press Enter"
        echo: false

    - name: start filebeat
      shell:
        cmd: "filebeat setup -e"

    - name: restart filebeat
      systemd:
        name: filebeat
        state: restarted
        enabled: true

    - name: install logstash
      apt:
        deb: "/usr/share/distrib/logstash-8.6.1-amd64.deb"
        state: present
        update_cache: true

    - name: filebeat configuring
      lineinfile:
        path: "{{ filebeat_conf }}"
        search_string: "{{ item.str }}"
        line: "{{ item.line }}"
      loop:
        - {str: 'output.elasticsearch:', line: '#output.elasticsearch:'}
        - {str: '  hosts: ["localhost:9200"]', line: '  #hosts: ["localhost:9200"]'}
        - {str: '#output.logstash:', line: 'output.logstash:'}
        - {str: '  #hosts: ["localhost:5044"]', line: '  hosts: ["localhost:5044"]'}

    - name: copy logstash test1 config to server
      copy:
        src: "./config/test1.conf"
        dest: "/etc/logstash/conf.d/"
      tags: reply

    - name: restart filebeat
      systemd:
        name: filebeat
        state: restarted

    - name: restart logstash
      systemd:
        name: logstash
        state: restarted
        enabled: true
      tags: reply

      

    


    